### PR TITLE
12 - Update header to match original site

### PR DESCRIPTION
**Pull request by tek08**

### CODE REVIEW

**Comment by tek08** [comment]
This doesn't currently have the Google Translate element, as Google seems to have turned off that feature for new sites.  Hunting down solution but holler if you know.

**Comment by tek08** [comment]
#12

**Comment by abbyhowell** [comment]
So the [test failures](https://circleci.com/gh/asylum-connect/asylumconnect-catalog/48) are telling us some useful things:

1) We need to update the Jest snapshots, and 2) server-side rendering is not impressed with this window-width setting maneuver.

**Comment by abbyhowell** [comment]
Related: https://github.com/asylum-connect/asylumconnect-catalog/issues/30

**Pull request closed without merging**
